services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: artifacts
    x-bake:
      output:
        - type=local,dest=release
      platforms:
        - linux/amd64
