services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: artifacts
      args:
        TAG: ${TAG}
    x-bake:
      output:
        - type=local,dest=release
      platforms:
        - linux/amd64
